import { supabase } from "@/integrations/supabase/client";

export type Modpack = {
  id: string;
  user_id: string;
  game_slug: string;
  name: string;
  description: string | null;
  share_code: string;
  is_public: boolean;
  download_count: number;
  created_at: string;
  updated_at: string;
};

export type ModpackMod = {
  id: string;
  modpack_id: string;
  mod_source: string;
  mod_id: string;
  mod_name: string;
  version: string | null;
  enabled: boolean;
  position: number;
};

export type InstalledMod = {
  id: string;
  user_id: string;
  game_slug: string;
  mod_source: string;
  mod_id: string;
  mod_name: string;
  version: string | null;
  install_path: string | null;
  installed_at: string;
};

export type ModpackWithMods = Modpack & { mods: ModpackMod[] };

export async function listModpacks(gameSlug: string): Promise<ModpackWithMods[]> {
  const { data: packs, error } = await supabase
    .from("modpacks")
    .select("*")
    .eq("game_slug", gameSlug)
    .order("updated_at", { ascending: false });
  if (error) throw error;
  if (!packs?.length) return [];
  const ids = packs.map((p) => p.id);
  const { data: mods, error: modsErr } = await supabase
    .from("modpack_mods")
    .select("*")
    .in("modpack_id", ids)
    .order("position", { ascending: true });
  if (modsErr) throw modsErr;
  return packs.map((p) => ({
    ...(p as Modpack),
    mods: ((mods ?? []) as ModpackMod[]).filter((m) => m.modpack_id === p.id),
  }));
}

export async function createModpack(input: {
  gameSlug: string;
  name: string;
  description?: string;
  isPublic?: boolean;
  mods?: Array<Omit<ModpackMod, "id" | "modpack_id" | "position"> & { position?: number }>;
}): Promise<ModpackWithMods> {
  const { data: userData } = await supabase.auth.getUser();
  const uid = userData?.user?.id;
  if (!uid) throw new Error("Not signed in");

  const { data: pack, error } = await supabase
    .from("modpacks")
    .insert({
      user_id: uid,
      game_slug: input.gameSlug,
      name: input.name,
      description: input.description ?? null,
      is_public: input.isPublic ?? false,
      // share_code auto-generated by trigger; satisfy NOT NULL with placeholder.
      share_code: "",
    } as never)
    .select("*")
    .single();
  if (error) throw error;

  let mods: ModpackMod[] = [];
  if (input.mods?.length) {
    const rows = input.mods.map((m, i) => ({
      modpack_id: pack.id,
      mod_source: m.mod_source,
      mod_id: m.mod_id,
      mod_name: m.mod_name,
      version: m.version ?? null,
      enabled: m.enabled ?? true,
      position: m.position ?? i,
    }));
    const { data: ins, error: mErr } = await supabase
      .from("modpack_mods")
      .insert(rows)
      .select("*");
    if (mErr) throw mErr;
    mods = (ins ?? []) as ModpackMod[];
  }
  return { ...(pack as Modpack), mods };
}

export async function updateModpack(id: string, patch: Partial<Pick<Modpack, "name" | "description" | "is_public">>) {
  const { error } = await supabase.from("modpacks").update(patch).eq("id", id);
  if (error) throw error;
}

export async function deleteModpack(id: string) {
  const { error } = await supabase.from("modpacks").delete().eq("id", id);
  if (error) throw error;
}

export async function redeemModpackCode(code: string): Promise<string> {
  const { data, error } = await supabase.rpc("redeem_modpack_code", { _code: code });
  if (error) throw error;
  return data as string;
}

export async function listInstalledMods(gameSlug: string): Promise<InstalledMod[]> {
  const { data, error } = await supabase
    .from("installed_mods")
    .select("*")
    .eq("game_slug", gameSlug)
    .order("installed_at", { ascending: false });
  if (error) throw error;
  return (data ?? []) as InstalledMod[];
}

export async function syncInstalledMods(
  gameSlug: string,
  mods: Array<Omit<InstalledMod, "id" | "user_id" | "game_slug" | "installed_at">>,
) {
  const { data: userData } = await supabase.auth.getUser();
  const uid = userData?.user?.id;
  if (!uid) return;
  // Replace strategy: delete existing for this user+game, then insert.
  await supabase.from("installed_mods").delete().eq("game_slug", gameSlug).eq("user_id", uid);
  if (!mods.length) return;
  await supabase.from("installed_mods").insert(
    mods.map((m) => ({
      user_id: uid,
      game_slug: gameSlug,
      mod_source: m.mod_source,
      mod_id: m.mod_id,
      mod_name: m.mod_name,
      version: m.version ?? null,
      install_path: m.install_path ?? null,
    })),
  );
}

export type LaunchPref = {
  user_id: string;
  game_id: string;
  last_mode: "vanilla" | "modded";
  active_modpack_id: string | null;
};

export async function getLaunchPref(gameId: string): Promise<LaunchPref | null> {
  const { data, error } = await supabase
    .from("game_launch_prefs")
    .select("*")
    .eq("game_id", gameId)
    .maybeSingle();
  if (error) throw error;
  return (data as LaunchPref | null) ?? null;
}

export async function setLaunchPref(input: {
  gameId: string;
  mode: "vanilla" | "modded";
  modpackId?: string | null;
}) {
  const { data: userData } = await supabase.auth.getUser();
  const uid = userData?.user?.id;
  if (!uid) return;
  await supabase
    .from("game_launch_prefs")
    .upsert({
      user_id: uid,
      game_id: input.gameId,
      last_mode: input.mode,
      active_modpack_id: input.modpackId ?? null,
    } as never);
}
