project_id = "ogkuwbdziljwbgspwoqp"

[functions.steam-import]
verify_jwt = false

[functions.rawg-search]
verify_jwt = false

[functions.steam-auth]
verify_jwt = false

[functions.spotify-auth]
verify_jwt = false

[functions.spotify-now-playing]
verify_jwt = false

[functions.steam-profile]
verify_jwt = false

[functions.rubix-accounts]
verify_jwt = false


